# Generated by Django 2.0.2 on 2018-05-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcy',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='btc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dash',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='doge',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['id'], 'permissions': (('view_invoice', 'Can view invoice'), ('pay_invoice', 'Can pay invoice'))},
        ),
        migrations.AlterModelOptions(
            name='ltc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['id'], 'permissions': (('view_payment', 'Can view payment'),)},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
