# Generated by Django 2.0.2 on 2018-05-26 09:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20180521_1340'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bcy',
            managers=[
                ('not_removed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='btc',
            managers=[
                ('not_removed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dash',
            managers=[
                ('not_removed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='doge',
            managers=[
                ('not_removed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ltc',
            managers=[
                ('not_removed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('not_removed', django.db.models.manager.Manager()),
            ],
        ),
    ]
