# Generated by Django 2.0.2 on 2018-04-25 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20180424_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sender_wallet_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('model', 'btc'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'ltc'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'dash'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'doge'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'bcy'), ('app_label', 'wallets'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='sended_invoices', to='contenttypes.ContentType'),
        ),
    ]
