# Generated by Django 2.0.2 on 2018-04-26 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import wallets.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20180424_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='expires',
            field=models.DateTimeField(default=wallets.utils.get_expires_date),
        )
    ]
