# Generated by Django 2.0.2 on 2018-05-01 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.db.models.query_utils
import django.utils.timezone
import model_utils.fields
import wallets.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('live', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Bcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('private', models.CharField(max_length=150, unique=True)),
                ('public', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150, unique=True)),
                ('wif', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcy_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Btc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('private', models.CharField(max_length=150, unique=True)),
                ('public', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150, unique=True)),
                ('wif', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btc_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('private', models.CharField(max_length=150, unique=True)),
                ('public', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150, unique=True)),
                ('wif', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dash_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('private', models.CharField(max_length=150, unique=True)),
                ('public', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150, unique=True)),
                ('wif', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doge_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('wallet_id', models.PositiveIntegerField()),
                ('tx_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('expires', models.DateTimeField(default=wallets.utils.get_expires_date)),
                ('wallet_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('model', 'btc'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'ltc'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'dash'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'doge'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'bcy'), ('app_label', 'wallets'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contenttypes.ContentType')),
            ],
            options={
                'permissions': (('view_invoice', 'Can view invoice'), ('pay_invoice', 'Can pay invoice')),
            },
        ),
        migrations.CreateModel(
            name='Ltc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('private', models.CharField(max_length=150, unique=True)),
                ('public', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150, unique=True)),
                ('wif', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltc_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet_id', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallets.Invoice')),
                ('wallet_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('model', 'btc'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'ltc'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'dash'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'doge'), ('app_label', 'wallets'), _connector='AND'), django.db.models.query_utils.Q(('model', 'bcy'), ('app_label', 'wallets'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'permissions': (('view_payment', 'Can view payment'),),
            },
        ),
    ]
